import { useMemo, useState } from 'react'
import { Plus, Search } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { Card } from '@/components/ui/Card'
import { ReportsTable } from '@/components/reports/ReportsTable'
import {
  GenerateReportModal,
  type GenerateReportFormValues,
} from '@/components/reports/GenerateReportModal'
import { ReportPreviewModal } from '@/components/reports/ReportPreviewModal'
import { initialReports } from '@/mocks/reports'
import type { Report, ReportStatus, ReportType } from '@/types/report'

const TYPE_LABELS: Record<ReportType, string> = {
  sales: 'Sales',
  traffic: 'Traffic',
  team_activity: 'Team Activity',
  custom: 'Custom',
}

const RANGE_METRICS: Record<'7' | '30' | '90', string> = {
  '7': 'Last 7 days',
  '30': 'Last 30 days',
  '90': 'Last 90 days',
}

let reportCounter = 0

export function ReportsPage() {
  const [reports, setReports] = useState<Report[]>(initialReports)
  const [search, setSearch] = useState('')
  const [statusFilter, setStatusFilter] = useState<ReportStatus | 'all'>('all')
  const [isGenerateOpen, setIsGenerateOpen] = useState(false)
  const [previewReport, setPreviewReport] = useState<Report | null>(null)

  const filteredReports = useMemo(() => {
    return reports.filter((report) => {
      const matchesSearch = report.name.toLowerCase().includes(search.toLowerCase())
      const matchesStatus = statusFilter === 'all' || report.status === statusFilter
      return matchesSearch && matchesStatus
    })
  }, [reports, search, statusFilter])

  const handleGenerate = (values: GenerateReportFormValues) => {
    reportCounter += 1
    const id = `r-new-${reportCounter}`
    const name = `${TYPE_LABELS[values.type]} Report — ${RANGE_METRICS[values.range]}`

    setReports((prev) => [
      {
        id,
        name,
        type: values.type,
        status: 'generating',
        createdAt: new Date().toISOString(),
        createdBy: 'You',
        metrics: [],
      },
      ...prev,
    ])

    setTimeout(() => {
      setReports((prev) =>
        prev.map((r) =>
          r.id === id
            ? {
                ...r,
                status: 'ready',
                metrics: [
                  { label: 'Total records', value: '1,204' },
                  { label: 'Date range', value: RANGE_METRICS[values.range] },
                  { label: 'Generated by', value: 'You' },
                ],
              }
            : r,
        ),
      )
    }, 1800)
  }

  const handleDelete = (report: Report) => {
    setReports((prev) => prev.filter((r) => r.id !== report.id))
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-lg font-semibold text-text-primary">Reports</h2>
          <p className="text-sm text-text-secondary">
            Generate and export reports on your business metrics
          </p>
        </div>
        <Button onClick={() => setIsGenerateOpen(true)}>
          <Plus className="size-4" />
          Generate report
        </Button>
      </div>

      <div className="flex flex-wrap gap-3">
        <div className="relative flex-1 min-w-48">
          <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-text-secondary" />
          <Input
            placeholder="Search reports..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>
        <Select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value as ReportStatus | 'all')}
          className="w-44"
        >
          <option value="all">All statuses</option>
          <option value="ready">Ready</option>
          <option value="generating">Generating</option>
          <option value="failed">Failed</option>
        </Select>
      </div>

      <Card>
        <ReportsTable
          reports={filteredReports}
          onView={setPreviewReport}
          onDelete={handleDelete}
        />
      </Card>

      <GenerateReportModal
        open={isGenerateOpen}
        onClose={() => setIsGenerateOpen(false)}
        onGenerate={handleGenerate}
      />
      <ReportPreviewModal report={previewReport} onClose={() => setPreviewReport(null)} />
    </div>
  )
}
